export const CAR_MODELS = {
  '-Kita-': ['Kita'],
  'A1 PRO': ['A1 PRO'],
  'Abarth': ['124 Spider', '500', '595', '695', 'Punto'],
  'AC': ['Cobra', 'Ace'],
  'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX', 'Integra', 'ZDX'],
  'Aito': ['M5', 'M7', 'M9'],
  'Aiways': ['U5', 'U6'],
  'Aixam': ['City', 'Coupe', 'Crossover', 'GTI', 'Mega City', 'Vision'],
  'Alfa Romeo': ['147', '156', '159', '166', '4C', 'Brera', 'Giulia', 'Giulietta', 'MiTo', 'Spider', 'Stelvio', 'Tonale'],
  'Alpina': ['B3', 'B4', 'B5', 'B7', 'B8', 'D3', 'D4', 'D5', 'XB7', 'XD3', 'XD4'],
  'Aston Martin': ['DB7', 'DB9', 'DB11', 'DB12', 'DBS', 'DBX', 'Rapide', 'Vantage', 'Vanquish', 'Virage'],
  'Audi': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q6 e-tron', 'Q7', 'Q8', 'Q8 e-tron', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'RS Q3', 'RS Q8', 'S1', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SQ5', 'SQ7', 'SQ8', 'TT', 'TTS', 'TT RS', 'e-tron', 'e-tron GT'],
  'BAW': ['Luba', 'Yuantu'],
  'BELLIER': ['Antelope', 'Jade', 'Opale'],
  'Bentley': ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX1', 'iX2', 'iX3', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z3', 'Z4'],
  'Bontu': ['Bontu'],
  'Buick': ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal', 'Verano'],
  'BYD': ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Song Plus', 'Tang', 'Yuan Plus'],
  'Cadillac': ['ATS', 'CTS', 'CT4', 'CT5', 'CT6', 'Escalade', 'LYRIQ', 'SRX', 'XT4', 'XT5', 'XT6'],
  'Casalini': ['Ydea', 'M14'],
  'Cenntro': ['Arcfox', 'Logistar'],
  'Chatenet': ['Barooder', 'CH26', 'CH30', 'CH32', 'Speedino'],
  'Chevrolet': ['Aveo', 'Blazer', 'Camaro', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Impala', 'Malibu', 'Silverado', 'Sonic', 'Suburban', 'Tahoe', 'Trailblazer', 'Trax'],
  'Chrysler': ['200', '300', 'Pacifica', 'PT Cruiser', 'Sebring', 'Town & Country', 'Voyager'],
  'Citroen': ['Berlingo', 'C1', 'C2', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C4 Picasso', 'C5', 'C5 Aircross', 'C5 X', 'C6', 'C8', 'Dispatch', 'DS3', 'DS4', 'DS5', 'Grand C4 Picasso', 'Jumpy', 'Nemo', 'Relay', 'Saxo', 'Spacetourer', 'Xsara'],
  'Cupra': ['Ateca', 'Born', 'Formentor', 'Leon', 'Tavascan', 'Terramar'],
  'Dacia': ['Duster', 'Jogger', 'Logan', 'Lodgy', 'Sandero', 'Spring', 'Bigster'],
  'Daihatsu': ['Charade', 'Copen', 'Cuore', 'Materia', 'Sirion', 'Terios', 'YRV'],
  'DFSK': ['Glory 580', 'Glory 330'],
  'Dodge': ['Challenger', 'Charger', 'Dart', 'Durango', 'Journey', 'Ram', 'Viper'],
  'Dongfeng': ['AX7', 'E70'],
  'DS Automobiles': ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 5', 'DS 7', 'DS 9'],
  'e.GO': ['Life'],
  'Ferrari': ['296', '488', '812', 'California', 'F8', 'LaFerrari', 'Portofino', 'Roma', 'SF90'],
  'Fiat': ['124 Spider', '500', '500C', '500e', '500L', '500X', 'Bravo', 'Doblo', 'Freemont', 'Grande Punto', 'Linea', 'Panda', 'Punto', 'Qubo', 'Tipo', 'Fullback'],
  'Fisker': ['Ocean', 'Pear'],
  'Ford': ['B-Max', 'C-Max', 'EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Galaxy', 'Grand C-Max', 'Ka', 'Ka+', 'Kuga', 'Mondeo', 'Mustang', 'Mustang Mach-E', 'Puma', 'Ranger', 'S-Max', 'Tourneo', 'Transit', 'Explorer'],
  'Forthing': ['T5 EVO', 'U-Tour'],
  'GAZ': ['Gazelle', 'Volga', '3110', 'Sobol'],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  'GMC': ['Acadia', 'Canyon', 'Envoy', 'Sierra', 'Terrain', 'Yukon'],
  'GWM': ['Haval H6', 'ORA', 'Poer', 'Wey Coffee'],
  'Honda': ['Accord', 'Civic', 'CR-V', 'CR-Z', 'e', 'e:Ny1', 'FR-V', 'HR-V', 'Jazz', 'Legend', 'NSX', 'Pilot', 'Ridgeline', 'S2000', 'ZR-V'],
  'Hongqi': ['E-HS9', 'H5', 'H9'],
  'Hummer': ['H1', 'H2', 'H3', 'EV'],
  'Hyundai': ['Accent', 'Bayon', 'Creta', 'Elantra', 'i10', 'i20', 'i30', 'i40', 'IONIQ', 'IONIQ 5', 'IONIQ 6', 'ix20', 'ix35', 'ix55', 'Kona', 'Matrix', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Staria', 'Terracan', 'Tucson', 'Veloster'],
  'IFA': ['W50', 'Trabant'],
  'Infiniti': ['EX', 'FX', 'G', 'M', 'Q30', 'Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80'],
  'Isuzu': ['D-Max', 'MU-X', 'Trooper'],
  'Iveco': ['Daily', 'Eurocargo', 'Massif', 'Stralis'],
  'Jaguar': ['E-Pace', 'E-Type', 'F-Pace', 'F-Type', 'I-Pace', 'S-Type', 'X-Type', 'XE', 'XF', 'XJ', 'XK'],
  'Jeep': ['Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Cherokee L', 'Patriot', 'Renegade', 'Wrangler'],
  'KGM': ['Korando', 'Musso', 'Rexton', 'Tivoli', 'Torres'],
  'Kia': ['Carens', 'Ceed', 'EV6', 'EV9', 'Niro', 'Optima', 'Picanto', 'ProCeed', 'Rio', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Stonic', 'Telluride', 'Venga', 'XCeed'],
  'Lada': ['Granta', 'Kalina', 'Largus', 'Niva', 'Priora', 'Vesta', '2101', '2105', '2107', '2110', '2114'],
  'Lamborghini': ['Aventador', 'Gallardo', 'Huracan', 'Revuelto', 'Urus'],
  'Lancia': ['Delta', 'Musa', 'Phedra', 'Thema', 'Voyager', 'Ypsilon'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'Lexus': ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'],
  'Ligier': ['IXO', 'JS60', 'JS50', 'Myli'],
  'Lincoln': ['Aviator', 'Corsair', 'MKC', 'MKT', 'MKX', 'MKZ', 'Nautilus', 'Navigator'],
  'Lotus': ['Elise', 'Emira', 'Evora', 'Exige', 'Eletre'],
  'LuAZ': ['969', 'LuAZ-1302'],
  'Lynk & Co': ['01', '02', '03', '05'],
  'MAN': ['TGE', 'TGL', 'TGM', 'TGS', 'TGX'],
  'Maserati': ['Ghibli', 'Grancabrio', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  'Maxus': ['Deliver 9', 'e Deliver 3', 'T60', 'MIFA 9'],
  'Maybach': ['GLS 600', 'S 580', 'S 680'],
  'Mazda': ['2', '3', '5', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-7', 'CX-9', 'MX-5', 'MX-30', 'RX-8'],
  'Mclaren': ['540C', '570S', '600LT', '620R', '650S', '675LT', '720S', '750S', 'Artura', 'GT', 'P1'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLK', 'CLS', 'E-Class', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'G-Class', 'GL', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'ML', 'S-Class', 'SL', 'SLK', 'SLS', 'Sprinter', 'V-Class', 'Vito'],
  'Mercury': ['Grand Marquis', 'Mountaineer'],
  'MG': ['3', '4', '5', 'HS', 'Marvel R', 'MG6', 'ZS', 'ZS EV'],
  'Microcar': ['Due', 'M.Go', 'MC1', 'MC2'],
  'Mini': ['Clubman', 'Convertible', 'Cooper', 'Cooper S', 'Countryman', 'Coupe', 'Electric', 'Hatch', 'Paceman', 'Roadster'],
  'Mitsubishi': ['ASX', 'Colt', 'Eclipse Cross', 'Galant', 'Grandis', 'L200', 'Lancer', 'Outlander', 'Pajero', 'Space Star'],
  'Moskvich': ['2141', '3', '6'],
  'Nissan': ['350Z', '370Z', 'Ariya', 'Juke', 'Leaf', 'Micra', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Pixo', 'Pulsar', 'Qashqai', 'Teana', 'Tiida', 'X-Trail'],
  'Opel': ['Adam', 'Agila', 'Ampera', 'Astra', 'Cascada', 'Combo', 'Corsa', 'Crossland', 'Frontera', 'Grandland', 'Insignia', 'Meriva', 'Mokka', 'Mokka-e', 'Omega', 'Signum', 'Vectra', 'Vivaro', 'Zafira'],
  'Peugeot': ['1007', '107', '108', '2008', '206', '207', '208', '3008', '301', '307', '308', '407', '408', '4007', '4008', '5008', '508', '607', 'Boxer', 'Expert', 'Partner', 'RCZ'],
  'Piaggio': ['Ape', 'Porter'],
  'Plymouth': ['Barracuda', 'Road Runner'],
  'Polestar': ['1', '2', '3', '4'],
  'Pontiac': ['Firebird', 'GTO', 'Solstice', 'Trans Am'],
  'Porsche': ['718', '911', '918', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  'RAM': ['1500', '2500', '3500', 'ProMaster'],
  'Renault': ['Arkana', 'Austral', 'Captur', 'Clio', 'Espace', 'Fluence', 'Grand Scenic', 'Kadjar', 'Kangoo', 'Koleos', 'Laguna', 'Megane', 'Megane E-Tech', 'Modus', 'Scenic', 'Symbol', 'Talisman', 'Twingo', 'Wind', 'Zoe'],
  'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Spectre', 'Wraith'],
  'Rover': ['25', '45', '75', 'City Rover', 'Street Wise'],
  'Saab': ['9-3', '9-5'],
  'Seat': ['Alhambra', 'Altea', 'Arona', 'Ateca', 'Cordoba', 'Exeo', 'Ibiza', 'Leon', 'Mii', 'Tarraco', 'Tavascan', 'Toledo'],
  'Seres': ['3', '5'],
  'Shuanghuan': ['CEO', 'Noble'],
  'Skoda': ['Citigo', 'Enyaq', 'Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Roomster', 'Scala', 'Superb', 'Yeti'],
  'Skut': ['Skut'],
  'Smart': ['#1', '#3', 'Fortwo', 'Forfour', 'Roadster'],
  'SsangYong': ['Actyon', 'Korando', 'Musso', 'Rexton', 'Rodius', 'Tivoli', 'XLV'],
  'Subaru': ['BRZ', 'Forester', 'Impreza', 'Legacy', 'Levorg', 'Outback', 'Solterra', 'Tribeca', 'WRX', 'XV'],
  'Suzuki': ['Alto', 'Baleno', 'Celerio', 'Grand Vitara', 'Ignis', 'Jimny', 'Kizashi', 'S-Cross', 'Splash', 'Swift', 'SX4', 'Vitara', 'Wagon R'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  'Toyota': ['Auris', 'Avensis', 'Aygo', 'C-HR', 'Camry', 'Corolla', 'GR86', 'GR Supra', 'GR Yaris', 'GT86', 'Highlander', 'Hilux', 'Land Cruiser', 'Mirai', 'Prius', 'ProAce', 'RAV4', 'Sequoia', 'Sienna', 'Supra', 'Tundra', 'Urban Cruiser', 'Verso', 'Yaris', 'Yaris Cross'],
  'Trabant': ['601', '1.1'],
  'UAZ': ['Hunter', 'Patriot', '469', 'Pickup'],
  'Vauxhall': ['Astra', 'Corsa', 'Insignia', 'Mokka', 'Vivaro'],
  'Volkswagen': ['Amarok', 'Arteon', 'Beetle', 'Caddy', 'California', 'Caravelle', 'CC', 'Crafter', 'Eos', 'Golf', 'Golf Sportsvan', 'Golf Variant', 'ID.3', 'ID.4', 'ID.5', 'ID.6', 'ID.7', 'Jetta', 'Multivan', 'Passat', 'Phaeton', 'Polo', 'Scirocco', 'Sharan', 'T-Cross', 'T-Roc', 'Tiguan', 'Tiguan Allspace', 'Touareg', 'Touran', 'Transporter', 'Up'],
  'Volvo': ['C30', 'C40', 'C70', 'EX30', 'EX40', 'EX90', 'S40', 'S60', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'],
  'Voyah': ['Dream', 'Free'],
  'Wartburg': ['353', '311'],
  'XEV': ['YOYO'],
  'Xpeng': ['G3', 'G6', 'G9', 'P5', 'P7'],
  'ZAZ': ['Lanos', 'Sens', 'Slavuta', 'Zaporozhets'],
  'Zeekr': ['001', '009', 'X'],
  'Zhidou': ['D1', 'D2', 'D3'],
};