export const modelsByMake = {
  Abarth: [
    { name: '124 Spider', count: 3 }, { name: '500', count: 12 }, { name: '595', count: 4 }, { name: 'Other', count: 1 },
  ],
  'Alfa Romeo': [
    { name: 'Giulia', count: 32 }, { name: 'Giulietta', count: 28 }, { name: 'MiTo', count: 10 },
    { name: 'Stelvio', count: 45 }, { name: 'Tonale', count: 22 }, { name: 'Other', count: 7 },
  ],
  'Aston Martin': [
    { name: 'DB11', count: 4 }, { name: 'DB9', count: 3 }, { name: 'DBS', count: 2 },
    { name: 'DBX', count: 4 }, { name: 'Vantage', count: 2 },
  ],
  Audi: [
    { name: '80', count: 2 }, { name: '90', count: 1 }, { name: 'A1', count: 522 },
    { name: 'A2', count: 1 }, { name: 'A3', count: 1771 }, { name: 'A4', count: 1207 },
    { name: 'A5', count: 632 }, { name: 'A6', count: 1305 }, { name: 'A6 Avant e-tron', count: 11 },
    { name: 'A6 Sportback e-tron', count: 16 }, { name: 'A7', count: 143 }, { name: 'A8', count: 48 },
    { name: 'e-tron', count: 94 }, { name: 'e-tron GT', count: 9 }, { name: 'e-tron GT quattro', count: 14 },
    { name: 'Q2', count: 336 }, { name: 'Q3', count: 517 }, { name: 'Q4', count: 7 },
    { name: 'Q4 e-tron', count: 124 }, { name: 'Q4 Sportback e-tron', count: 2 }, { name: 'Q5', count: 455 },
    { name: 'Q5 Sportback', count: 1 }, { name: 'Q6 e-tron', count: 26 }, { name: 'Q7', count: 213 },
    { name: 'Q8', count: 52 }, { name: 'Q8 e-tron', count: 18 }, { name: 'R8', count: 1 },
    { name: 'RS e-tron GT', count: 1 }, { name: 'RS Q3', count: 4 }, { name: 'RS Q8', count: 1 },
    { name: 'RS3', count: 9 }, { name: 'RS4', count: 10 }, { name: 'RS5', count: 18 },
    { name: 'RS6', count: 3 }, { name: 'S1', count: 1 }, { name: 'S3', count: 93 },
    { name: 'S4', count: 11 }, { name: 'S5', count: 15 }, { name: 'S6', count: 7 },
    { name: 'S7', count: 3 }, { name: 'S8', count: 1 }, { name: 'SQ5', count: 11 },
    { name: 'SQ7', count: 8 }, { name: 'TT', count: 90 }, { name: 'Other', count: 4 },
  ],
  Bentley: [
    { name: 'Bentayga', count: 12 }, { name: 'Continental', count: 18 }, { name: 'Flying Spur', count: 10 },
    { name: 'Mulsanne', count: 5 },
  ],
  BMW: [
    { name: '1 Series', count: 1420 }, { name: '2 Series', count: 780 }, { name: '3 Series', count: 1650 },
    { name: '4 Series', count: 620 }, { name: '5 Series', count: 1100 }, { name: '6 Series', count: 180 },
    { name: '7 Series', count: 240 }, { name: '8 Series', count: 95 }, { name: 'iX', count: 130 },
    { name: 'iX1', count: 85 }, { name: 'iX3', count: 70 }, { name: 'i3', count: 145 },
    { name: 'i4', count: 88 }, { name: 'i5', count: 42 }, { name: 'i7', count: 28 },
    { name: 'M2', count: 55 }, { name: 'M3', count: 62 }, { name: 'M4', count: 48 },
    { name: 'M5', count: 35 }, { name: 'M8', count: 12 }, { name: 'X1', count: 590 },
    { name: 'X2', count: 310 }, { name: 'X3', count: 720 }, { name: 'X4', count: 220 },
    { name: 'X5', count: 480 }, { name: 'X6', count: 175 }, { name: 'X7', count: 95 },
    { name: 'Z4', count: 88 }, { name: 'Other', count: 120 },
  ],
  BYD: [
    { name: 'Atto 3', count: 145 }, { name: 'Dolphin', count: 88 }, { name: 'Han', count: 22 },
    { name: 'Seal', count: 165 }, { name: 'Seal U', count: 55 }, { name: 'Sealion 6', count: 40 },
    { name: 'Tang', count: 0 },
  ],
  Chevrolet: [
    { name: 'Aveo', count: 8 }, { name: 'Captiva', count: 6 }, { name: 'Cruze', count: 5 }, { name: 'Other', count: 6 },
  ],
  Citroen: [
    { name: 'Berlingo', count: 185 }, { name: 'C1', count: 145 }, { name: 'C3', count: 320 },
    { name: 'C3 Aircross', count: 145 }, { name: 'C4', count: 188 }, { name: 'C4 Cactus', count: 92 },
    { name: 'C5', count: 45 }, { name: 'C5 Aircross', count: 132 }, { name: 'C5 X', count: 28 },
    { name: 'Dispatch', count: 65 }, { name: 'e-C4', count: 55 }, { name: 'Jumpy', count: 40 },
    { name: 'Other', count: 79 },
  ],
  Cupra: [
    { name: 'Born', count: 88 }, { name: 'Formentor', count: 285 }, { name: 'Leon', count: 125 },
    { name: 'Tavascan', count: 44 },
  ],
  Dacia: [
    { name: 'Duster', count: 480 }, { name: 'Jogger', count: 185 }, { name: 'Logan', count: 65 },
    { name: 'Sandero', count: 395 }, { name: 'Sandero Stepway', count: 172 }, { name: 'Spring', count: 0 },
  ],
  'DS Automobiles': [
    { name: 'DS 3', count: 38 }, { name: 'DS 3 Crossback', count: 42 }, { name: 'DS 4', count: 22 },
    { name: 'DS 7', count: 15 }, { name: 'DS 9', count: 4 },
  ],
  Fiat: [
    { name: '500', count: 245 }, { name: '500C', count: 45 }, { name: '500L', count: 28 },
    { name: '500X', count: 85 }, { name: '500e', count: 55 }, { name: 'Bravo', count: 12 },
    { name: 'Doblo', count: 32 }, { name: 'Ducato', count: 42 }, { name: 'Grande Punto', count: 8 },
    { name: 'Panda', count: 62 }, { name: 'Tipo', count: 14 }, { name: 'Other', count: 0 },
  ],
  Ford: [
    { name: 'C-Max', count: 185 }, { name: 'EcoSport', count: 142 }, { name: 'Edge', count: 88 },
    { name: 'Explorer', count: 32 }, { name: 'Fiesta', count: 820 }, { name: 'Focus', count: 685 },
    { name: 'Galaxy', count: 95 }, { name: 'Kuga', count: 455 }, { name: 'Mondeo', count: 245 },
    { name: 'Mustang', count: 55 }, { name: 'Mustang Mach-E', count: 88 }, { name: 'Puma', count: 320 },
    { name: 'Ranger', count: 145 }, { name: 'S-Max', count: 112 }, { name: 'Transit', count: 220 },
    { name: 'Transit Custom', count: 185 }, { name: 'Other', count: 247 },
  ],
  Honda: [
    { name: 'Accord', count: 65 }, { name: 'Civic', count: 420 }, { name: 'CR-V', count: 285 },
    { name: 'e', count: 35 }, { name: 'e:Ny1', count: 22 }, { name: 'HR-V', count: 145 },
    { name: 'Jazz', count: 210 }, { name: 'Legend', count: 8 }, { name: 'Other', count: 594 },
  ],
  Hyundai: [
    { name: 'i10', count: 385 }, { name: 'i20', count: 420 }, { name: 'i30', count: 580 },
    { name: 'i40', count: 55 }, { name: 'IONIQ', count: 245 }, { name: 'IONIQ 5', count: 320 },
    { name: 'IONIQ 6', count: 145 }, { name: 'Kona', count: 485 }, { name: 'Nexo', count: 5 },
    { name: 'Santa Fe', count: 285 }, { name: 'Staria', count: 12 }, { name: 'Tucson', count: 620 },
    { name: 'Other', count: 817 },
  ],
  Jaguar: [
    { name: 'E-Pace', count: 88 }, { name: 'F-Pace', count: 112 }, { name: 'F-Type', count: 45 },
    { name: 'I-Pace', count: 65 }, { name: 'XE', count: 55 }, { name: 'XF', count: 48 },
    { name: 'XJ', count: 15 }, { name: 'Other', count: 0 },
  ],
  Jeep: [
    { name: 'Avenger', count: 42 }, { name: 'Cherokee', count: 22 }, { name: 'Compass', count: 35 },
    { name: 'Gladiator', count: 8 }, { name: 'Grand Cherokee', count: 28 }, { name: 'Renegade', count: 28 },
    { name: 'Wrangler', count: 0 },
  ],
  Kia: [
    { name: 'Ceed', count: 385 }, { name: 'EV3', count: 22 }, { name: 'EV6', count: 285 },
    { name: 'EV9', count: 45 }, { name: 'Niro', count: 245 }, { name: 'Picanto', count: 320 },
    { name: 'ProCeed', count: 55 }, { name: 'Sorento', count: 185 }, { name: 'Sportage', count: 620 },
    { name: 'Stinger', count: 28 }, { name: 'Stonic', count: 145 }, { name: 'Xceed', count: 120 },
    { name: 'Other', count: 850 },
  ],
  'Land Rover': [
    { name: 'Defender', count: 245 }, { name: 'Discovery', count: 185 }, { name: 'Discovery Sport', count: 285 },
    { name: 'Freelander', count: 32 }, { name: 'Range Rover', count: 220 }, { name: 'Range Rover Evoque', count: 320 },
    { name: 'Range Rover Sport', count: 185 }, { name: 'Range Rover Velar', count: 140 },
  ],
  Lexus: [
    { name: 'CT', count: 55 }, { name: 'IS', count: 88 }, { name: 'LC', count: 12 },
    { name: 'LS', count: 18 }, { name: 'LX', count: 8 }, { name: 'NX', count: 125 },
    { name: 'RX', count: 95 }, { name: 'UX', count: 79 }, { name: 'Other', count: 0 },
  ],
  Mazda: [
    { name: 'CX-3', count: 145 }, { name: 'CX-30', count: 188 }, { name: 'CX-5', count: 285 },
    { name: 'CX-60', count: 55 }, { name: 'Mazda2', count: 145 }, { name: 'Mazda3', count: 245 },
    { name: 'Mazda6', count: 85 }, { name: 'MX-5', count: 82 }, { name: 'MX-30', count: 44 },
    { name: 'Other', count: 0 },
  ],
  'Mercedes-Benz': [
    { name: 'A-Class', count: 520 }, { name: 'B-Class', count: 245 }, { name: 'C-Class', count: 680 },
    { name: 'CLA', count: 185 }, { name: 'CLK', count: 22 }, { name: 'CLS', count: 55 },
    { name: 'E-Class', count: 420 }, { name: 'EQA', count: 88 }, { name: 'EQB', count: 55 },
    { name: 'EQC', count: 45 }, { name: 'EQE', count: 32 }, { name: 'EQS', count: 18 },
    { name: 'G-Class', count: 35 }, { name: 'GLA', count: 245 }, { name: 'GLB', count: 125 },
    { name: 'GLC', count: 320 }, { name: 'GLE', count: 185 }, { name: 'GLS', count: 65 },
    { name: 'ML', count: 45 }, { name: 'S-Class', count: 88 }, { name: 'SL', count: 22 },
    { name: 'SLC', count: 15 }, { name: 'Sprinter', count: 85 }, { name: 'V-Class', count: 55 },
    { name: 'Other', count: 165 },
  ],
  MG: [
    { name: 'MG3', count: 45 }, { name: 'MG4', count: 88 }, { name: 'MG5', count: 32 },
    { name: 'MG ZS', count: 95 }, { name: 'ZS EV', count: 39 },
  ],
  Mini: [
    { name: 'Clubman', count: 85 }, { name: 'Convertible', count: 55 }, { name: 'Cooper', count: 245 },
    { name: 'Countryman', count: 185 }, { name: 'Paceman', count: 18 }, { name: 'Roadster', count: 12 },
    { name: 'Other', count: 242 },
  ],
  Mitsubishi: [
    { name: 'ASX', count: 125 }, { name: 'Eclipse Cross', count: 88 }, { name: 'L200', count: 45 },
    { name: 'Outlander', count: 145 }, { name: 'Outlander PHEV', count: 110 }, { name: 'Other', count: 39 },
  ],
  Nissan: [
    { name: 'Ariya', count: 65 }, { name: 'Juke', count: 485 }, { name: 'Leaf', count: 420 },
    { name: 'Micra', count: 285 }, { name: 'Navara', count: 112 }, { name: 'Note', count: 145 },
    { name: 'Pathfinder', count: 22 }, { name: 'Qashqai', count: 820 }, { name: 'X-Trail', count: 380 },
    { name: 'Other', count: 1013 },
  ],
  Opel: [
    { name: 'Adam', count: 55 }, { name: 'Agila', count: 18 }, { name: 'Astra', count: 420 },
    { name: 'Cascada', count: 12 }, { name: 'Corsa', count: 580 }, { name: 'Crossland', count: 145 },
    { name: 'Grandland', count: 185 }, { name: 'Insignia', count: 145 }, { name: 'Meriva', count: 32 },
    { name: 'Mokka', count: 245 }, { name: 'Mokka-e', count: 88 }, { name: 'Vivaro', count: 65 },
    { name: 'Zafira', count: 55 }, { name: 'Other', count: 378 },
  ],
  Peugeot: [
    { name: '107', count: 22 }, { name: '108', count: 88 }, { name: '2008', count: 285 },
    { name: '208', count: 480 }, { name: '3008', count: 345 }, { name: '308', count: 320 },
    { name: '4008', count: 15 }, { name: '408', count: 65 }, { name: '5008', count: 145 },
    { name: '508', count: 88 }, { name: 'e-208', count: 145 }, { name: 'e-2008', count: 88 },
    { name: 'Expert', count: 45 }, { name: 'Partner', count: 88 }, { name: 'Rifter', count: 55 },
    { name: 'Other', count: 609 },
  ],
  Porsche: [
    { name: '718', count: 28 }, { name: '911', count: 55 }, { name: 'Cayenne', count: 88 },
    { name: 'Cayenne Coupé', count: 32 }, { name: 'Macan', count: 75 }, { name: 'Panamera', count: 35 },
    { name: 'Taycan', count: 0 },
  ],
  Renault: [
    { name: 'Arkana', count: 88 }, { name: 'Austral', count: 55 }, { name: 'Captur', count: 345 },
    { name: 'Clio', count: 580 }, { name: 'Espace', count: 18 }, { name: 'Kadjar', count: 125 },
    { name: 'Kangoo', count: 88 }, { name: 'Megane', count: 320 }, { name: 'Megane E-Tech', count: 65 },
    { name: 'Scenic', count: 88 }, { name: 'Trafic', count: 55 }, { name: 'Twingo', count: 45 },
    { name: 'Zoe', count: 145 }, { name: 'Other', count: 558 },
  ],
  SEAT: [
    { name: 'Arona', count: 245 }, { name: 'Ateca', count: 185 }, { name: 'Ibiza', count: 420 },
    { name: 'Leon', count: 520 }, { name: 'Mii', count: 22 }, { name: 'Tarraco', count: 88 },
    { name: 'Toledo', count: 12 }, { name: 'Other', count: 311 },
  ],
  Skoda: [
    { name: 'Citigo', count: 45 }, { name: 'Enyaq', count: 285 }, { name: 'Enyaq Coupé', count: 88 },
    { name: 'Fabia', count: 520 }, { name: 'Kamiq', count: 145 }, { name: 'Karoq', count: 245 },
    { name: 'Kodiaq', count: 185 }, { name: 'Octavia', count: 780 }, { name: 'Rapid', count: 55 },
    { name: 'Scala', count: 88 }, { name: 'Superb', count: 245 }, { name: 'Other', count: 585 },
  ],
  Subaru: [
    { name: 'Forester', count: 28 }, { name: 'Impreza', count: 18 }, { name: 'Legacy', count: 8 },
    { name: 'Outback', count: 32 }, { name: 'XV', count: 19 },
  ],
  Suzuki: [
    { name: 'Alto', count: 22 }, { name: 'Baleno', count: 35 }, { name: 'Celerio', count: 28 },
    { name: 'Ignis', count: 88 }, { name: 'Jimny', count: 65 }, { name: 'S-Cross', count: 145 },
    { name: 'Swift', count: 320 }, { name: 'Vitara', count: 285 }, { name: 'Other', count: 143 },
  ],
  Tesla: [
    { name: 'Cybertruck', count: 2 }, { name: 'Model 3', count: 88 }, { name: 'Model S', count: 22 },
    { name: 'Model X', count: 18 }, { name: 'Model Y', count: 51 },
  ],
  Toyota: [
    { name: 'Aygo', count: 285 }, { name: 'Aygo X', count: 145 }, { name: 'bZ4X', count: 55 },
    { name: 'C-HR', count: 320 }, { name: 'Camry', count: 22 }, { name: 'Corolla', count: 620 },
    { name: 'GR86', count: 12 }, { name: 'GR Yaris', count: 18 }, { name: 'Highlander', count: 15 },
    { name: 'Land Cruiser', count: 45 }, { name: 'Proace', count: 55 }, { name: 'Prius', count: 88 },
    { name: 'RAV4', count: 420 }, { name: 'Supra', count: 8 }, { name: 'Urban Cruiser', count: 22 },
    { name: 'Verso', count: 28 }, { name: 'Yaris', count: 520 }, { name: 'Yaris Cross', count: 185 },
    { name: 'Other', count: 1121 },
  ],
  Vauxhall: [
    { name: 'Astra', count: 145 }, { name: 'Corsa', count: 220 }, { name: 'Crossland', count: 55 },
    { name: 'Grandland', count: 75 }, { name: 'Insignia', count: 88 }, { name: 'Mokka', count: 82 },
    { name: 'Other', count: 0 },
  ],
  Volkswagen: [
    { name: 'Amarok', count: 88 }, { name: 'Arteon', count: 145 }, { name: 'Caddy', count: 185 },
    { name: 'California', count: 55 }, { name: 'Caravelle', count: 65 }, { name: 'Crafter', count: 120 },
    { name: 'Golf', count: 1850 }, { name: 'Golf Variant', count: 145 }, { name: 'ID.3', count: 245 },
    { name: 'ID.4', count: 320 }, { name: 'ID.5', count: 88 }, { name: 'ID.7', count: 42 },
    { name: 'Passat', count: 620 }, { name: 'Polo', count: 780 }, { name: 'Scirocco', count: 35 },
    { name: 'Sharan', count: 85 }, { name: 'T-Cross', count: 285 }, { name: 'T-Roc', count: 520 },
    { name: 'Tiguan', count: 820 }, { name: 'Touareg', count: 145 }, { name: 'Touran', count: 165 },
    { name: 'Transporter', count: 285 }, { name: 'Up!', count: 88 }, { name: 'Other', count: 1578 },
  ],
  Volvo: [
    { name: 'C40', count: 88 }, { name: 'EX30', count: 55 }, { name: 'EX40', count: 42 },
    { name: 'EX90', count: 18 }, { name: 'S60', count: 65 }, { name: 'S90', count: 32 },
    { name: 'V40', count: 88 }, { name: 'V60', count: 145 }, { name: 'V90', count: 78 },
    { name: 'XC40', count: 320 }, { name: 'XC60', count: 385 }, { name: 'XC90', count: 245 },
    { name: 'Other', count: 377 },
  ],
};

export const popularModelsByMake = {
  Audi: [
    { name: 'A3', count: 1771 }, { name: 'A6', count: 1305 }, { name: 'A4', count: 1207 },
    { name: 'A5', count: 632 }, { name: 'A1', count: 522 },
  ],
  BMW: [
    { name: '3 Series', count: 1650 }, { name: '1 Series', count: 1420 }, { name: '5 Series', count: 1100 },
    { name: 'X3', count: 720 }, { name: 'X5', count: 480 },
  ],
  Ford: [
    { name: 'Fiesta', count: 820 }, { name: 'Focus', count: 685 }, { name: 'Kuga', count: 455 },
    { name: 'Puma', count: 320 }, { name: 'Mondeo', count: 245 },
  ],
  Hyundai: [
    { name: 'Tucson', count: 620 }, { name: 'i30', count: 580 }, { name: 'Kona', count: 485 },
    { name: 'i20', count: 420 }, { name: 'i10', count: 385 },
  ],
  Kia: [
    { name: 'Sportage', count: 620 }, { name: 'Ceed', count: 385 }, { name: 'Niro', count: 245 },
    { name: 'Picanto', count: 320 }, { name: 'Sorento', count: 185 },
  ],
  'Mercedes-Benz': [
    { name: 'C-Class', count: 680 }, { name: 'A-Class', count: 520 }, { name: 'E-Class', count: 420 },
    { name: 'GLC', count: 320 }, { name: 'GLA', count: 245 },
  ],
  Nissan: [
    { name: 'Qashqai', count: 820 }, { name: 'Juke', count: 485 }, { name: 'Leaf', count: 420 },
    { name: 'X-Trail', count: 380 }, { name: 'Micra', count: 285 },
  ],
  Opel: [
    { name: 'Corsa', count: 580 }, { name: 'Astra', count: 420 }, { name: 'Mokka', count: 245 },
    { name: 'Grandland', count: 185 }, { name: 'Crossland', count: 145 },
  ],
  Renault: [
    { name: 'Clio', count: 580 }, { name: 'Megane', count: 320 }, { name: 'Captur', count: 345 },
    { name: 'Zoe', count: 145 }, { name: 'Kadjar', count: 125 },
  ],
  Skoda: [
    { name: 'Octavia', count: 780 }, { name: 'Fabia', count: 520 }, { name: 'Superb', count: 245 },
    { name: 'Enyaq', count: 285 }, { name: 'Karoq', count: 245 },
  ],
  Toyota: [
    { name: 'Yaris', count: 520 }, { name: 'Corolla', count: 620 }, { name: 'RAV4', count: 420 },
    { name: 'C-HR', count: 320 }, { name: 'Yaris Cross', count: 185 },
  ],
  Volkswagen: [
    { name: 'Golf', count: 1850 }, { name: 'Tiguan', count: 820 }, { name: 'Polo', count: 780 },
    { name: 'Passat', count: 620 }, { name: 'T-Roc', count: 520 },
  ],
  Volvo: [
    { name: 'XC60', count: 385 }, { name: 'XC40', count: 320 }, { name: 'XC90', count: 245 },
    { name: 'V60', count: 145 }, { name: 'V40', count: 88 },
  ],
};