import React from 'react';
import { useLang } from '@/lib/LangContext';
import { t } from '@/lib/i18n';

const makes = [
  { name: '-Kita-', count: '11' },
  { name: 'A1 PRO', count: '1' },
  { name: 'Abarth', count: '4' },
  { name: 'AC', count: '1' },
  { name: 'Acura', count: '8' },
  { name: 'Aito', count: '1' },
  { name: 'Aiways', count: '1' },
  { name: 'Aixam', count: '66' },
  { name: 'Alfa Romeo', count: '85' },
  { name: 'Alpina', count: '5' },
  { name: 'Aston Martin', count: '13' },
  { name: 'Audi', count: '3,540' },
  { name: 'BAW', count: '1' },
  { name: 'BELLIER', count: '1' },
  { name: 'Bentley', count: '51' },
  { name: 'BMW', count: '6,055' },
  { name: 'Bontu', count: '1' },
  { name: 'Buick', count: '35' },
  { name: 'BYD', count: '8' },
  { name: 'Cadillac', count: '40' },
  { name: 'Casalini', count: '1' },
  { name: 'Cenntro', count: '1' },
  { name: 'Chatenet', count: '12' },
  { name: 'Chevrolet', count: '222' },
  { name: 'Chrysler', count: '231' },
  { name: 'Citroen', count: '913' },
  { name: 'Cupra', count: '100' },
  { name: 'Dacia', count: '148' },
  { name: 'Daihatsu', count: '5' },
  { name: 'DFSK', count: '1' },
  { name: 'Dodge', count: '306' },
  { name: 'Dongfeng', count: '2' },
  { name: 'DS Automobiles', count: '47' },
  { name: 'e.GO', count: '1' },
  { name: 'Ferrari', count: '6' },
  { name: 'Fiat', count: '282' },
  { name: 'Fisker', count: '3' },
  { name: 'Ford', count: '2,028' },
  { name: 'Forthing', count: '2' },
  { name: 'GAZ', count: '17' },
  { name: 'Genesis', count: '1' },
  { name: 'GMC', count: '10' },
  { name: 'GWM', count: '5' },
  { name: 'Honda', count: '436' },
  { name: 'Hongqi', count: '1' },
  { name: 'Hummer', count: '8' },
  { name: 'Hyundai', count: '724' },
  { name: 'IFA', count: '1' },
  { name: 'Infiniti', count: '58' },
  { name: 'Isuzu', count: '7' },
  { name: 'Iveco', count: '93' },
  { name: 'Jaguar', count: '207' },
  { name: 'Jeep', count: '372' },
  { name: 'KGM', count: '4' },
  { name: 'Kia', count: '782' },
  { name: 'Lada', count: '16' },
  { name: 'Lamborghini', count: '11' },
  { name: 'Lancia', count: '15' },
  { name: 'Land Rover', count: '519' },
  { name: 'Lexus', count: '644' },
  { name: 'Ligier', count: '48' },
  { name: 'Lincoln', count: '15' },
  { name: 'Lotus', count: '1' },
  { name: 'LuAZ', count: '1' },
  { name: 'Lynk & Co', count: '6' },
  { name: 'MAN', count: '34' },
  { name: 'Maserati', count: '51' },
  { name: 'Maxus', count: '3' },
  { name: 'Maybach', count: '3' },
  { name: 'Mazda', count: '445' },
  { name: 'Mclaren', count: '7' },
  { name: 'Mercedes-Benz', count: '3,489' },
  { name: 'Mercury', count: '2' },
  { name: 'MG', count: '27' },
  { name: 'Microcar', count: '29' },
  { name: 'Mini', count: '285' },
  { name: 'Mitsubishi', count: '270' },
  { name: 'Moskvich', count: '3' },
  { name: 'Nissan', count: '1,015' },
  { name: 'Opel', count: '1,844' },
  { name: 'Peugeot', count: '1,423' },
  { name: 'Piaggio', count: '1' },
  { name: 'Plymouth', count: '3' },
  { name: 'Polestar', count: '17' },
  { name: 'Pontiac', count: '2' },
  { name: 'Porsche', count: '639' },
  { name: 'RAM', count: '7' },
  { name: 'Renault', count: '1,082' },
  { name: 'Rolls-Royce', count: '7' },
  { name: 'Rover', count: '2' },
  { name: 'Saab', count: '41' },
  { name: 'Seat', count: '377' },
  { name: 'Seres', count: '2' },
  { name: 'Shuanghuan', count: '1' },
  { name: 'Skoda', count: '1,374' },
  { name: 'Skut', count: '2' },
  { name: 'Smart', count: '14' },
  { name: 'SsangYong', count: '24' },
  { name: 'Subaru', count: '453' },
  { name: 'Suzuki', count: '75' },
  { name: 'Tesla', count: '231' },
  { name: 'Toyota', count: '2,389' },
  { name: 'Trabant', count: '1' },
  { name: 'UAZ', count: '4' },
  { name: 'Vauxhall', count: '1' },
  { name: 'Volkswagen', count: '4,416' },
  { name: 'Volvo', count: '2,314' },
  { name: 'Voyah', count: '1' },
  { name: 'Wartburg', count: '1' },
  { name: 'XEV', count: '2' },
  { name: 'Xpeng', count: '4' },
  { name: 'ZAZ', count: '6' },
  { name: 'Zeekr', count: '4' },
  { name: 'Zhidou', count: '10' },
];

export default function PopularMakes() {
  const { lang } = useLang();
  return (
    <section className="max-w-7xl mx-auto px-4 py-12 md:py-16">
      <h2 className="text-2xl md:text-3xl font-bold text-center text-foreground mb-8">{t(lang, 'makes_title')}</h2>
      <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 gap-3">
        {makes.map((make) => (
          <button key={make.name} className="flex flex-col items-center justify-center bg-card rounded-xl border border-border p-4 hover:border-primary/40 hover:shadow-md transition-all duration-200 group">
            <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center mb-2 group-hover:bg-primary/20 transition-colors">
              <span className="text-primary font-bold text-sm">{make.name[0]}</span>
            </div>
            <span className="text-xs font-semibold text-foreground text-center leading-tight">{make.name}</span>
            <span className="text-[10px] text-muted-foreground mt-0.5">{make.count} cars</span>
          </button>
        ))}
      </div>
    </section>
  );
}